src/Entity/Bobines.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\BobinesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BobinesRepository::class)]
#[ApiResource(security : "is_granted('ROLE_USER')")]
class Bobines
{
    public final const RESULT_PER_PAGE = 30;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $poids = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_ajout = null;

    #[ORM\ManyToOne(inversedBy: 'bobines')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Couleur $couleur = null;

    #[ORM\ManyToOne(inversedBy: 'bobines')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'bobines')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $gestionnaire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoids(): ?float
    {
        return $this->poids;
    }

    public function setPoids(float $poids): static
    {
        $this->poids = $poids;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): static
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getCouleur(): ?Couleur
    {
        return $this->couleur;
    }

    public function setCouleur(?Couleur $couleur): static
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getGestionnaire(): ?Users
    {
        return $this->gestionnaire;
    }

    public function setGestionnaire(?Users $gestionnaire): static
    {
        $this->gestionnaire = $gestionnaire;

        return $this;
    }
}

src/Entity/Categorie.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
#[ApiResource]
class Categorie
{
    public function __toString(): String{
        return $this->getNomType();
    }


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_type = null;

    #[ORM\Column(length: 255)]
    private ?string $propriete = null;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Bobines::class)]
    private Collection $bobines;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Impressions::class)]
    private Collection $impressions;

    public function __construct()
    {
        $this->bobines = new ArrayCollection();
        $this->impressions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomType(): ?string
    {
        return $this->nom_type;
    }

    public function setNomType(string $nom_type): static
    {
        $this->nom_type = $nom_type;

        return $this;
    }

    public function getPropriete(): ?string
    {
        return $this->propriete;
    }

    public function setPropriete(string $propriete): static
    {
        $this->propriete = $propriete;

        return $this;
    }

    /**
     * @return Collection<int, Bobines>
     */
    public function getBobines(): Collection
    {
        return $this->bobines;
    }

    public function addBobine(Bobines $bobine): static
    {
        if (!$this->bobines->contains($bobine)) {
            $this->bobines->add($bobine);
            $bobine->setCategorie($this);
        }

        return $this;
    }

    public function removeBobine(Bobines $bobine): static
    {
        if ($this->bobines->removeElement($bobine)) {
            // set the owning side to null (unless already changed)
            if ($bobine->getCategorie() === $this) {
                $bobine->setCategorie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Impressions>
     */
    public function getImpressions(): Collection
    {
        return $this->impressions;
    }

    public function addImpression(Impressions $impression): static
    {
        if (!$this->impressions->contains($impression)) {
            $this->impressions->add($impression);
            $impression->setCategorie($this);
        }

        return $this;
    }

    public function removeImpression(Impressions $impression): static
    {
        if ($this->impressions->removeElement($impression)) {
            // set the owning side to null (unless already changed)
            if ($impression->getCategorie() === $this) {
                $impression->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Entity/Imprimantes.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ImprimantesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImprimantesRepository::class)]
#[ApiResource]
class Imprimantes
{


    public final const RESULT_PER_PAGE = 30;


    public function __toString(): String{
        return $this->getNomImprimante();
    }
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $type_imprimante = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_imprimante = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deleted = null;

    #[ORM\OneToMany(mappedBy: 'imprimantes', targetEntity: Impressions::class)]
    private Collection $impression;

    #[ORM\ManyToOne(inversedBy: 'imprimantes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $username = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_ajout = null;

    public function __construct()
    {
        $this->impression = new ArrayCollection();
        $this->date_ajout = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeImprimante(): ?string
    {
        return $this->type_imprimante;
    }

    public function setTypeImprimante(string $type_imprimante): static
    {
        $this->type_imprimante = $type_imprimante;

        return $this;
    }

    public function getNomImprimante(): ?string
    {
        return $this->nom_imprimante;
    }

    public function setNomImprimante(string $nom_imprimante): static
    {
        $this->nom_imprimante = $nom_imprimante;

        return $this;
    }

    public function getDeleted(): ?\DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?\DateTimeInterface $deleted): static
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * @return Collection<int, Impressions>
     */
    public function getImpression(): Collection
    {
        return $this->impression;
    }

    public function addImpression(Impressions $impression): static
    {
        if (!$this->impression->contains($impression)) {
            $this->impression->add($impression);
            $impression->setImprimantes($this);
        }

        return $this;
    }

    public function removeImpression(Impressions $impression): static
    {
        if ($this->impression->removeElement($impression)) {
            // set the owning side to null (unless already changed)
            if ($impression->getImprimantes() === $this) {
                $impression->setImprimantes(null);
            }
        }

        return $this;
    }

    public function getUsername(): ?Users
    {
        return $this->username;
    }

    public function setUsername(?Users $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): static
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }
}

src/Controller/user/VenteController.php
<?php

namespace App\Controller\user;


use App\Entity\Clients;
use App\Entity\Ventes;
use App\Form\AjoutclientFormType;
use App\Form\VentesFormType;
use App\Repository\ClientsRepository;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[IsGranted('ROLE_USER')]
#[Route(path: "/user/vente")]

class VenteController extends AbstractController
{
    #[Route('/', name: 'caisse_user')]
    public function caisse(Request $request, EntityManagerInterface $entityManager): Response
    {

        $ventes = new Ventes();
        $form = $this->createForm(VentesFormType::class, $ventes);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ventes->setVendeur(
                $this->getUser()
            );
            $ventes->setDateVente(
                new \DateTime('now')
            );

            $entityManager->persist($ventes);
            $entityManager->flush();

            return $this->redirectToRoute('ventes_user');
        }
        return $this->render('user/Vente/caisse.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/nouvclient', name: 'addclient_user')]
    public function client(Request $request, EntityManagerInterface $entityManager): Response
    {
        $client = new Clients();
        $form = $this->createForm(AjoutclientFormType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $client->setDateInscription(
                new \DateTime('now')
            );

            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('caisse_user');
        }
        return $this->render('user/Vente/addclients.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/clients', name: 'listclient_user')]
    public function lclient(ClientsRepository $clientsRepository): Response
    {

        return $this->render('user/Vente/listclient.html.twig', [
            'clients'=>$clientsRepository->findAll(),
        ]);
    }
}

templates/user/gestion/ajoutbobine.html.twig
{% extends 'base.html.twig' %}
{% block title %}Centre de contrôle{% endblock %}


{% block body%}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
                <h4 class="card-title">Ajout de bobines</h4>
                <p class="card-description"> Ajoutez vos bobines au stock </p>
            <div class="forms-sample">
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <div class="form-group">
                    {{ form_row(form.poids) }}
                    </div>
                <div class="form-group">
                    {{ form_row(form.prix)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.couleur)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.categorie)}}
                </div>
                <input type="submit" class="btn btn-primary mr-2" value="Envoyer" />
                {{ form_end(form) }}
                </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/gestion/ajoutimpression.html.twig
{% extends 'base.html.twig' %}
{% block title %}Centre de contrôle{% endblock %}


{% block body%}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
                <h4 class="card-title">Ajout d'impression</h4>
                <p class="card-description"> Ajoutez vos impressions éffectués </p>
            <div class="forms-sample">
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <div class="form-group">
                    {{ form_row(form.couleur) }}
                    </div>
                <div class="form-group">
                    {{ form_row(form.categorie)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.poids)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.imprimantes)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.temps)}}
                </div>
                <input type="submit" class="btn btn-primary mr-2" value="Envoyer" />
                {{ form_end(form) }}
                </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/gestion/ajoutimprimante.html.twig
{% extends 'base.html.twig' %}
{% block title %}Centre de contrôle{% endblock %}


{% block body%}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
                <h4 class="card-title">Ajout d'impimantes</h4>
                <p class="card-description"> Ajoutez vos Imprimantes a la plateforme </p>
            <div class="forms-sample">
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <div class="form-group">
                    {{ form_row(form.type_imprimante) }}
                    </div>
                <div class="form-group">
                    {{ form_row(form.marque)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.prix)}}
                </div>
                <div class="form-group">
                    {{ form_row(form.nom_imprimante)}}
                </div>
                <input type="submit" class="btn btn-primary mr-2" value="Envoyer" />
                {{ form_end(form) }}
                </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/gestion/impressions.html.twig
{% extends 'base.html.twig' %}
{% block title %}Impressions{% endblock %}


{% block body %}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Impressions Effectués</h4>
            <a href="{{ path('ajoutimpress_user') }}" class="btn btn-primary">Ajouter une impression</a>
            <div class="small-pagination text-right">

					{% set current_page = app.request.query.get('page', 1) %}
					{% set total_items = impressions_count %}
					{% set result_per_page = constant('App\\Entity\\Impressions::RESULT_PER_PAGE') %}
					{% set total_page = (impressions_count / result_per_page)|round(0, 'ceil') %}

					{{ current_page * result_per_page - result_per_page + 1 }}
					-
					{{ current_page * result_per_page > total_items ? total_items :current_page * result_per_page }}
					sur
					{{ total_items }}

					<a class="pointer pagination-control {% if current_page == 1 %}disabled{% endif %}" href="{{ path('impression_user', { page: 1 }) }}">
						<i class="bi bi-chevron-double-left bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if current_page == 1 %}disabled{% endif %}" href="{{ path('impression_user', { page: current_page - 1 }) }}">
						<i class="bi bi-chevron-left bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if total_items - (result_per_page * current_page) < 1 %}disabled{% endif %}" href="{{ path('impression_user', { page: current_page + 1 }) }}">
						<i class="bi bi-chevron-right bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if current_page == total_page %}disabled{% endif %}" href="{{ path('impression_user', { page: total_page }) }}">
						<i class="bi bi-chevron-double-right bi-lg"></i>
					</a>
				</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> Utilisateur </th>
                        <th> Imprimante </th>
                        <th> Poids </th>
                        <th> Catégorie </th>
                        <th> Couleur </th>
                        <th> Durée </th>
                        <th> Date impression </th>
                    </tr>
                </thead>
                <tbody>
                    {% for impression in impressions %}
                    <tr>
                        <td class="py-1">
                            {{impression.utilisateur.username }}
                        </td>
                        <td class="py-1"> {{ impression.Imprimantes }} </td>
                        <td>
                            {{ impression.poids }}
                        </td>
                        <td class="py-1">
                        
                            {{ impression.categorie.nomType }}
                        </td>
                        <td class="py-1">
                            {{ impression.Couleur.nom }}
                        </td>
                        <td class="py-1"> {{impression.Temps|date('H:m')}} </td>
                        <td class="py-1">
                            {{ impression.Date|date('d/m/Y') }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/user/gestion/imprimantes.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% endblock %}


{% block body%}
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">Imprimante possédées</h4>
				<a href="{{ path('ajoutimpri_user') }}" class="btn btn-primary">Ajouter une imprimante</a>
				<div class="small-pagination text-right">

					{% set current_page = app.request.query.get('page', 1) %}
					{% set total_items = imprimantes_count %}
					{% set result_per_page = constant('App\\Entity\\Imprimantes::RESULT_PER_PAGE') %}
					{% set total_page = (imprimantes_count / result_per_page)|round(0, 'ceil') %}

					{{ current_page * result_per_page - result_per_page + 1 }}
					-
					{{ current_page * result_per_page > total_items ? total_items :current_page * result_per_page }}
					sur
					{{ total_items }}

					<a class="pointer pagination-control {% if current_page == 1 %}disabled{% endif %}" href="{{ path('imprimante_user', { page: 1 }) }}">
						<i class="bi bi-chevron-double-left bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if current_page == 1 %}disabled{% endif %}" href="{{ path('imprimante_user', { page: current_page - 1 }) }}">
						<i class="bi bi-chevron-left bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if total_items - (result_per_page * current_page) < 1 %}disabled{% endif %}" href="{{ path('imprimante_user', { page: current_page + 1 }) }}">
						<i class="bi bi-chevron-right bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if current_page == total_page %}disabled{% endif %}" href="{{ path('imprimante_user', { page: total_page }) }}">
						<i class="bi bi-chevron-double-right bi-lg"></i>
					</a>
				</div>
				<table class="table table-striped">
					<thead>
						<tr>
							<th>
								Date d'ajout
							</th>
							<th>
								Utilisateur
							</th>
							<th>
								Imprimante
							</th>
							<th>
								Marque
							</th>
							<th>
								Prix
							</th>
							<th>
								Nom
							</th>
							<th>
								Désactivée le
							</th>
							<th>
								Actions
							</th>
						</tr>
					</thead>
					<tbody>
						{% for printer in imprimantes %}
							<tr>
								<td class="py-1">
									{{printer.dateAjout|date('d/m/Y') }}
								</td>
								<td class="py-1">
									{{printer.username }}
								</td>
								<td>
									{{ printer.nomImprimante }}
								</td>
								<td>
									{{ printer.Marque }}
								</td>
								<td>
									{{ printer.Prix }}€
								</td>
								<td>
									{{ printer.typeImprimante }}
								</td>
								<td>
									{{printer.deleted ? printer.deleted|date('d/m/Y-H:m') : 'Imprimante Active' }}
								</td>
								<td>
									{% if printer.deleted == null %}
										<form method="get" action="{{ path('imprimante_desactiver_user', {'id': printer.id}) }}">
											<button class="btn btn-primary" type="submit">Désactiver</button>
										</form>
									{% else %}
										<p>Aucune actions disponibles</p>
									{% endif %}


								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock %}

templates/user/gestion/stock.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% endblock %}



{% block body%}
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">Stocks disponibles</h4>
				<a href="{{ path('ajoutb_user') }}" class="btn btn-primary">Ajouter une bobine</a>

				<div class="small-pagination text-right">

					{% set current_page = app.request.query.get('page', 1) %}
					{% set total_items = Bobines_count %}
					{% set result_per_page = constant('App\\Entity\\Bobines::RESULT_PER_PAGE') %}
					{% set total_page = (Bobines_count / result_per_page)|round(0, 'ceil') %}

					{{ current_page * result_per_page - result_per_page + 1 }}
					-
					{{ current_page * result_per_page > total_items ? total_items :current_page * result_per_page }}
					sur
					{{ total_items }}

					<a class="pointer pagination-control {% if current_page == 1 %}disabled{% endif %}" href="{{ path('stock_user', { page: 1 }) }}">
						<i class="bi bi-chevron-double-left bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if current_page == 1 %}disabled{% endif %}" href="{{ path('stock_user', { page: current_page - 1 }) }}">
						<i class="bi bi-chevron-left bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if total_items - (result_per_page * current_page) < 1 %}disabled{% endif %}" href="{{ path('stock_user', { page: current_page + 1 }) }}">
						<i class="bi bi-chevron-right bi-lg"></i>
					</a>
					<a class="pointer pagination-control {% if current_page == total_page %}disabled{% endif %}" href="{{ path('stock_user', { page: total_page }) }}">
						<i class="bi bi-chevron-double-right bi-lg"></i>
					</a>
				</div>

				<table class="table table-striped">
					<thead>
						<tr>
							<th>
								Utilisateur
							</th>
							<th>
								poids
							</th>
							<th>
								Couleur
							</th>
							<th>
								Catégorie
							</th>
							<th>
								Prix
							</th>
							<th>Date d'ajout</th>
						</tr>
					</thead>
					<tbody>
						{% for stock in stocks %}
							<tr>
								<td class="py-1">
									{{stock.gestionnaire.username }}
								</td>
								<td>
									{{ stock.poids }}
									Kg
								</td>
								<td>
									{{ stock.couleur.nom }}
								</td>
								<td>
									{{stock.categorie.nomType }}
								</td>
								<td>
									{{stock.prix }}
									€
								</td>
								<td>
									{{stock.dateAjout|date('d/m/Y') }}
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock %}